eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

spring:
  data:
    redis:
      host: localhost
      port: 6379
#      username: default
#      password: default