server:
  port: 19091

spring:
  profiles:
    default: local
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        pool:
          max-connections: 200
          max-idle-time: 20s
        connect-timeout: 20000
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**

      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}